# Generated by Django 4.0.2 on 2022-03-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskreminder_email_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreminder',
            name='email_time',
        ),
    ]
