# Generated by Django 4.0.2 on 2022-03-06 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_taskreminder_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreminder',
            name='last_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 9, 25, 11, 847523)),
        ),
    ]
