# Generated by Django 4.0.2 on 2022-03-06 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_taskreminder_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreminder',
            name='last_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 11, 10, 4, 254220, tzinfo=utc)),
        ),
    ]
